title : Automated Ramblings
description: ''

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
plugins: 
  - jekyll-gist
  - jekyll-paginate

exclude:
  - gulp_config
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - s3_website.yml
  - build-and-push.sh
  - .java-version
  - .vscode
  - node_modules
  - package-lock.json
  - package.json
  
permalink: BrettsITBlog/:year/:month/:title.html

# Google Analytics
google_analytics: UA-77455242-1